services:
  - type: web
    name: network-cell-analyzer-server
    env: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APP_TIMEZONE
        value: Asia/Beirut
